# Public inputs
guessA = "1"
guessB = "2"
guessC = "3"
guessD = "4"
numBlow = "2"
numHit = "1"
publicSolutionHash = "0x17df526bf4b433952da1be4573e3be254cdd8d695aff821e75f86c833a592954"

# Private inputs
salt = "42"
solutionA = "2"
solutionB = "1"
solutionC = "3"
solutionD = "5"
